#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DIR"
cwd=${PWD##*/}
echo $cwd
if [ "$cwd" = "Frogger-master" ]
then
	cd ..
	rm -Rf Frogger-master
	rm Frogger-master.zip
	git clone https://github.com/kentdlee/Frogger
fi

